image: Visual Studio 2017

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}

build_script:
  - python create_venv.py create --group test
  - venv\\Scripts\\genbuildinfo "epyqlib\\_build.py"
  - ps: Update-AppveyorBuild -Version "v$(venv\\Scripts\\python -c 'import epyqlib; print(epyqlib.__version__, end=\"\")') b$Env:APPVEYOR_BUILD_NUMBER"

test_script:
  - venv\\Scripts\\pytest -vvvv -s --no-qt-log --run-factory epyqlib.tests --pyargs

deploy_script:
  - python create_venv.py publish

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
