version: 2

jobs:
  linux:
    docker:
      - image: circleci/python:3.7
    environment:
      PYTHON: python3
    steps:
      - checkout

      - run:
          name: Prepare
          command: |
            bash .circleci/prepare.sh
            sudo apt update
            sudo apt install p7zip-full
            sudo sed -i 's/.*\(en_US\.UTF-8 UTF-8\)/\1/' /etc/locale.gen
            sudo locale-gen
      - run:
          name: Test
          command: |
            bash .circleci/test.sh

  osx:
    macos:
      xcode: "10.0.0"
    environment:
      PYTHON: python3
    steps:
      - checkout

      - run:
          name: Prepare
          command: |
            bash .circleci/prepare.sh
            brew update
            brew install p7zip
      - run:
          name: Test
          command: |
            bash .circleci/test.sh

workflows:
  version: 2
  all:
    jobs:
      - linux
      - osx
